version: '3.8'

services:
  snailwatch:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: snailwatch-app
    restart: unless-stopped
    ports:
      - "3000:3000"  # Expose port 3000 for NGINX to connect
    networks:
      - app-network
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  app-network:
    driver: bridge
    name: snailwatch-network
